---
- name: This is a hello-world example
  hosts: test-servers
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: Hellooo World!!!!
        dest: /tmp/testfile.txt
